<div class="filter-parent filter-label-parent filter-standard-parent filter-twocol-parent">
  <a href="javascript:void(0)" class="filter-link filter-label-link">Labels</a>
  <div class="filter-drop filter-label-drop">
    <a href="javascript:void(0)" class="filter-drop-reset-link">Reset</a>
    <ul class="filter-label-drop-list">
        <?php foreach ($labels as $entry):?>
        <li class="filter-type-drop-list-item">
            <input name="<?= $entry['id']?>" id="fg-label-<?= $entry['id']?>" class="filter-drop-checkbox" type="checkbox">
            <label for="fg-label-<?= $entry['id']?>" class="filter-drop-checkbox-label"><?= $entry['name']?> <span class="filter-item-count"><?= $entry['cnt']?></span></label>
        </li>
        <?php endforeach;?>
    </ul>
  </div>
</div>