<?php use Application\Entity\Track;
$this->headScript()->appendFile($this->basePath('plugins/DataTables/datatables.min.js'));
$this->headlink()->appendStylesheet($this->basePath('plugins/DataTables/datatables.min.css'))?>
<?php 
if(isset($title)) $this->headTitle($title);
?>
<form method="post" id="form">
<div class="page-header">
    <div class="container-fluid">
      <div class="pull-right">
        <button type="button" data-toggle="tooltip" title="" class="btn btn-primary" onclick="confirm('Are you sure?') ? $('#form').submit() : false;" data-original-title="Submit"><i class="fa fa-check-square-o"></i> Submit</button>
        <a href="<?= $this->url('backend/default',['action' => 'import'])?>" data-toggle="tooltip" title="" class="btn btn-default" data-original-title="Cancel"><i class="fa fa-reply"></i></a>
      </div>
      <h1>Import</h1>
    </div>
</div>
<div class="container-fluid">
    <?= $this->showMessages()?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-list"></i> Imported List</h3>
        </div>
        <div class="panel-body">
           <div class="table-responsive">
                <table id="table-data" class="table table-bordered table-hover" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                          <td class="text-left" style="width:25px">#</td>
                          <td class="text-left">Title</td>
                          <td class="text-left">Format</td>
                          <td class="text-left">Artists</td>
                          <td class="text-left">Label</td>
                          <td class="text-left">Genre</td>     
                          <td class="text-left">Album</td>     
                          <td class="text-left">Released</td>      
                          <td class="text-left">Cover</td>                          
                        </tr>
                      </thead>
                    <tbody>
                        <?php foreach ($data as $key => $entry):?>
                        <?php $track = $entry['track']; $errors = $entry['errors']; $warnings = $entry['warnings'];?>
                        <?php 
                        if(isset($entry['success'])) 
                            $class = 'bg-success text-success';
                        else
                            $class = (!empty($errors))?'bg-danger':((!empty($warnings))?'bg-warning':'');
                        ?>
                        <tr class="<?= $class?>">
                            <td><?= $key+1?></td>
                            <td><?= isset($track['title'])?$track['title']:''?></td>
                            <td><?= $track['fileFormat']?></td>
                            <td><?= (isset($track['artists_string']))?$track['artists_string']:''?></td>
                            <td><?= (isset($track['label']))?$track['label']:''?></td>
                            <td><?= (isset($track['genre']))?$track['genre']:''?></td>
                            <td><?= (isset($track['album']))?$track['album']:'';?></td>
                            <td><?= $track['publishDate']->format('Y-m-d')?></td>
                            <td><?= (isset($track['picture']))?'Yes':'No';?></td>
                        </tr>
                        <?php if(!empty($warnings)):?>
                        <tr class="bg-warning text-warning">
                            <td></td>
                            <td colspan="8"><?= implode(' ',$warnings)?></td>
                        </tr>
                        <?php endif;?>
                        <?php if(!empty($errors)):?>
                        <tr class="bg-danger text-danger">
                            <td></td>
                            <td colspan="8"><?= implode(' ',$errors)?></td>
                        </tr>
                        <?php endif;?>
                        <?php endforeach;?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
</form>
        
<?php $this->inlineScript()->captureStart();
echo <<<JS
$(function() {
     $('#table-data').DataTable( {
         "columnDefs": [ {
          "targets"  : 'no-sort',
          "orderable": false,
          "order": []
        }],
        "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]]
    } );
});
JS;
$this->inlineScript()->captureEnd();
?>