<?php 
if(isset($title)) $this->headTitle($title);
$form->prepare();
echo $this->form()->openTag($form);?>
<div class="page-header">
    <div class="container-fluid">
      <div class="pull-right">
        <button type="submit" name="submit" data-toggle="tooltip" title="" class="btn btn-primary" data-original-title="Save"><i class="fa fa-save"></i></button>
        <a href="<?= $this->url('backend')?>" data-toggle="tooltip" title="" class="btn btn-default" data-original-title="Cancel"><i class="fa fa-reply"></i></a>
      </div>
      <h1>Setting</h1>
    </div>
</div>
<div class="container-fluid">
    <?= $this->showMessages()?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-list"></i> Setting Update</h3>
        </div>
        <div class="panel-body">
            <?= $this->formRow($form->get('id'));?>
            <?= $this->formRow($form->get('code'));?>
            <?= $this->formRow($form->get('value'));?>
        </div>
    </div>
</div>
<?= $this->form()->closeTag();?>