<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html lang="en">
<!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta name="robots" content="index, follow">
	<title><?= $title?></title>   
	<meta name="description" content="<?= $description?>" />	
	<meta property="og:type" content="website" />
	<meta property="og:locale" content="en_US" />
	<meta property="og:title" content="<?= $title?>" />
	<meta property="og:description" content="<?= $description?>" />
	<?php if(isset($image)):?>
	<meta property="og:image" content="<?= $image?>" />
    <meta name="twitter:image" content="<?= $image?>" />
    <?php endif;?>		
	<meta name="twitter:card" content="player" />
    <meta name="twitter:site" content="@whoPlayMusic" />
    <meta name="twitter:title" content="<?= $title?>" />
    <meta name="twitter:description" content="<?= $description?>" />
</head>
<body>
</body>