<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Who Play Music')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/screen.css?v=0.0.0.1'))
            //->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?php $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <div class="header-container">
            <header class="header">
                <a class="logo" href="<?= $this->url('home')?>">WhoPlayMusic</a>                  
                <div class="nav navbar-nav">
                    <?= $this->navigation('default')->menu() ?>
                  </div>
            </header>
        </div>
        <main class="main">
            <div class="main-content">
            <?= $this->content ?>
            </div>
        </main>
        <footer class="footer">
            <div class="footer-content"></div>
        </footer>       
<?= $this->headScript();?>
<?php $this->inlineScript()->captureStart();
echo <<<JS
JS;
$this->inlineScript()->captureEnd();
?>   
        <?= $this->inlineScript() ?>
    </body>
</html>