<?= $this->doctype() ?>
<html lang="en" ng-app>
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Who Play Music')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/screen.css?v=0.0.0.1'))
            //->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

    </head>
    <body>
        <?= $this->content ?>
    </body>
</html>