<div class="header-container">
    <div class="header-bg-wrap">
        <div class="head-mobile-nav">
            <div class="mobile-menu-icon">
                <svg class="icon-menu" width="25" height="25">
                  <path d="M0,5 25,5" stroke="#fff" stroke-width="4"/>
                  <path d="M0,13 25,13" stroke="#fff" stroke-width="4"/>
                  <path d="M0,21 25,21" stroke="#fff" stroke-width="4"/>
                </svg>
                <span class="icon-close">
                    <svg viewBox="0 0 40 40">
                      <path class="close-x" d="M 10,10 L 30,30 M 30,10 L 10,30"/>
                    </svg>
                </span>
              </div>
              <div class="mobile-menu-body">
              </div>
        </div>
        <header class="header">
            <a href="" class="beatport-logo">
                <svg viewBox="0 0 200 200" alt="Beatport" class="logo-icon logo-icon-default">
                <use xlink:href="/static/images/defs.svg#logo-headphones"/>
                </svg>
                <svg viewBox="0 0 200 200" alt="Beatport" class="logo-icon logo-icon-loading">
                  <!-- NOTE: Chrome does not currently support animations in externally loaded svgs, so we must define this here -->
                  <g>
                    <path d="M172.6,99.6 C172.6,59.6 140,27 100,27 C60,27 27.4,59.6 27.4,99.6
                      C27.4,118.1 34.4,135.8 47.1,149.3 L47.1,149.3 C48.8,151.1 51.6,151.2
                      53.5,149.5 L61.3,142.1 C63.1,140.4 63.2,137.6 61.5,135.8 L61.5,135.8
                      C52.3,126 47.2,113.1 47.2,99.7 C47.2,70.6 70.9,46.9 100,46.9 C129.1,46.9
                      152.8,70.6 152.8,99.7 C152.8,113.2 147.7,126 138.5,135.8 L138.5,135.8
                      C136.8,137.6 136.9,140.4 138.7,142.1 L146.5,149.5 C148.3,151.2 151.2,151.1
                      152.9,149.3 L152.9,149.3 C165.6,135.7 172.6,118.1 172.6,99.6">
                      <animateTransform attributeName="transform" type="rotate" from="360 100 100" to="0 100 100" begin="0s" dur="1.2s" values="360 100 100;3 100 100;-3 100 100;0 100 100;0 100 100" keySplines="
                          .5 0 .8 1;
                          0 0 1 1;
                          0 0 1 1;
                          0 0 1 1" keyTimes="0;0.5;0.57;0.64;1" calcMode="spline" repeatCount="indefinite"/>
                    </path>
                    <g>
                      <path d="M200,99.2 C200,89.3 198.5,79.6 195.6,70.2 L195.6,70.2 L195.6,70.2
                        C194.8,67.9 192.3,66.6 190,67.3 L179.7,70.5 C177.3,71.2 176,73.7
                        176.7,76.1 L176.7,76.1 C179,83.6 180.2,91.3 180.2,99.2 C180.2,113.2
                        176.4,126.8 169.3,138.8 L169.3,138.8 C168,140.9 168.7,143.7 170.9,144.9
                        L180.1,150.4 C182.2,151.7 185,151 186.3,148.9 C195.3,134
                        200,116.8 200,99.2"/>
                      <path d="M30.7,138.8 C23.6,126.9 19.8,113.2 19.8,99.2 C19.8,91.3 21,83.5
                        23.3,76.1 L23.3,76.1 C24,73.7 22.7,71.2 20.3,70.5 L10,67.3 C7.6,66.6
                        5.1,67.9 4.4,70.2 L4.4,70.2 C1.5,79.6 0,89.3 0,99.2 C0,116.8 4.8,134
                        13.7,149 L13.7,149 C15,151.1 17.7,151.8 19.9,150.5 L29.1,145 C31.2,143.7
                        31.9,140.9 30.7,138.8 L30.7,138.8 L30.7,138.8 Z"/>
                      <animateTransform attributeName="transform" type="rotate" from="0 100 100" to="360 100 100" begin="0s" dur="1.2s" values="0 100 100;363 100 100;357 100 100;360 100 100;360 100 100" keySplines="
                          .5 0 .8 1;
                          0 0 1 1;
                          0 0 1 1;
                          0 0 1 1" keyTimes="0;0.5;0.57;0.64;1" calcMode="spline" repeatCount="indefinite"/>
                    </g>
                  </g>
                </svg>
                        <svg viewBox="0 0 935.5 200" alt="Beatport" class="logo-type">
                  <use xlink:href="/static/images/defs.svg#logo-type"/>
                </svg>
              </a>
              <div class="nav-links"></div>
              <div class="header-icons">
                <div class="head-parent head-account-parent">
                    <span data-href="/account/djprofile" class="head-account-link">
                      <svg viewBox="0 0 200 200" class="head-account-icon" style="display: none;">
                        <use xlink:href="/static/images/defs.svg#icon-user"/>
                      </svg>
                      <span class="head-account-user-image"></span>
                      <span class="head-account-default-image" style="display: inline-block;"></span>
                      <span class="head-account-content">byrkas</span>
                    </span>
                    <div class="head-drop account-drop header-tooltip-menu">
                      <div class="account-drop-logged-out" style="display: none;">
                        <h2>Welcome to Beatport</h2>
                        <p>Beatport is the world's largest electronic music store for DJs</p>
                        <a href="/account/signup" class="button button--large">Create an Account</a>
                        <div class="account-drop-log-in-parent">
                          <h6 class="account-drop-heading account-drop-log-in-heading"><span class="deco"></span><span class="text">Already have an account? Sign in</span></h6>
                          <form class="modal-login-signup-form" onsubmit="return false">
                            <p class="login-form-error-message"><span class="icon icon-dead-robot-head"></span><span class="login-form-error-message-text">Invalid login. Please try again.</span></p>
                            <input name="username" placeholder="Username" class="account-drop-username" required="" type="text">
                            <input name="password" placeholder="Password" class="account-drop-password" required="" type="password">
                            <div class="login-remember-parent">
                              <div class="remember-me-parent">
                                <input class="remember-me-checkbox" type="checkbox">
                                <label class="remember-me-label">Remember me</label>
                              </div>
                              <input class="blue-button" value="Log In" type="submit">
                            </div>
                            <div class="forgot-login-link-parent">
                              <a href="/account/forgot-password" class="forgot-login-link">Forgot your username or password?</a>
                            </div>
                          </form>
                        </div>
                      </div>
                      <div class="account-drop-logged-in" style="display: block;">
                        <a href="/account/djprofile">Account Settings</a>
                        <a href="/downloads/available">My Downloads</a>
                        <a href="/dj/charts/unpublished">My Charts</a>
                        <a class="log-out" href="#">Log Out</a>
                      </div>
                    </div>
                  </div>
                  <div class="search">
                        <!-- Mobile Search -->
                        <a href="#" class="mobile-search-launch-link">
                          <svg viewBox="0 0 200 200" class="head-search-icon">
                            <use xlink:href="/static/images/defs.svg#icon-search"/>
                          </svg>
                        </a>
                        <div class="mobile-search-parent">
                          <div class="mobile-search">
                            <input placeholder="SEARCH..." class="mobile-search-input" type="search">
                          </div>
                          <a href="#" class="mobile-cancel-search-link">Cancel</a>
                        </div>
                        <!-- End Mobile Search -->
                
                        <div class="head-search-parent ">
                  <div class="head-search">
                    <svg viewBox="0 0 200 200" class="head-decorative-search-icon">
                      <use xlink:href="/static/images/defs.svg#icon-search"/>
                    </svg>
                    <span class="twitter-typeahead" style="direction: ltr;"><input class="head-search-input tt-hint" style="background: rgba(0, 0, 0, 0) none repeat scroll 0% 0%;" readonly="" autocomplete="off" spellcheck="false" tabindex="-1" type="search"><input placeholder="SEARCH..." class="head-search-input tt-input" autocomplete="off" spellcheck="false" dir="auto" type="search"><pre aria-hidden="true" style="position: absolute; visibility: hidden; white-space: pre; font-family: &quot;CoreSans&quot;,Arial,sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: 400; word-spacing: 0px; letter-spacing: 1px; text-indent: 0px; text-rendering: optimizelegibility; text-transform: none;"></pre><span class="tt-dropdown-menu"><div class="tt-dataset-default"></div></span></span>
                  </div>
                  <a href="#" class="mobile-cancel-search-link">Cancel</a>
                </div>
                      </div>
              </div>
        </header>
    </div>
</div>